[project]
name = "ai_code_assistant"
version = "0.0.1"
description = "LongbowXXX's ai code assistant."
authors = [
    { name = "LongbowXXX" },
]
readme = "README.md"
license = { text = "MIT" }
keywords = [
    "llm",
]
classifiers = [
    "Programming Language :: Python :: 3.11",
]
requires-python = "==3.11.*"
dependencies = [
    "python-dotenv>=1.0.1",
    "langchain>=0.2.12",
    "langchain-community>=0.2.11",
    "langgraph>=0.2.3",
    "openai>=1.40.3",
    "chromadb>=0.5.5",
    "langchain-openai>=0.1.2",
    "langchain-google-genai>=1.0.8",
    "langchain-google-community>=1.0.7",
    "langchain-aws>=0.1.16",
    "langchainhub>=0.1.20",
    "types-requests>=2.32.0.20240712",
    "mesop>=0.11.1"
]

[project.optional-dependencies]
dev = [
    "black>=24.8.0",
    "flake8>=7.1.1",
    "flake8-copyright>=0.2.4",
    "mypy>=1.11.1",
    "pytest>=8.3.2",
    "pytest-asyncio>=0.23.8",
    "pytest-cov>=5.0.0",
    "respx>=0.21.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
plugins = []
ignore_missing_imports = true
strict = true
follow_imports = "normal"
strict_optional = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "mesop.*"
ignore_missing_imports = true

[tool.black]
target-version = ["py310"]
line-length = 120

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["agent", "agent.*"]
